=== oscar-cluster/oscar/packages/package.dtd
<!ELEMENT package (name,version,class,installable,summary,
                   license,copyright?,group,url?,maintainer*,
                   packager+,vendor?,description,provides*,requires*,
                   switcher*,rpmlist*,oda?)>

<!--
The easiest way to use this file and to validate the XML files config.xml is
to use the xmllint software that is avalaible with the libxml library (package
avalaible for all? distro.

In order to check your XML syntax, you can just make a
xmllint config.xml
to ensure that you produce correct XML.

In order to validate against this DTD you can do a
xmllint -\-valid config.xml
This will format the document to STDOUT, errors will be at the beginning of
the document.

To test the valididy (against the present DTD) you can use the -\-noout option
(if all is correct, xmllint will produce no output).

For instance, from this directory
xmllint -\-valid -\-noout */config.xml

Will show you all the packages that don't validate against the present DTD.
-->

<!ELEMENT name (#PCDATA)>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT version (major,minor,subversion,release,epoch)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT minor (#PCDATA)>
<!ELEMENT subversion (#PCDATA)>
<!ELEMENT release (#PCDATA)>
<!ELEMENT epoch (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT installable (#PCDATA)>
<!ELEMENT license (#PCDATA)>
<!ELEMENT copyright (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT maintainer (name,email)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT packager (name,email)>
<!ELEMENT vendor (#PCDATA)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT description (#PCDATA)>


<!ELEMENT provides (type,name)>
<!ELEMENT type (#PCDATA)>

<!ELEMENT requires (type,name)>

<!ELEMENT switcher (tag,name)>
<!ELEMENT tag (#PCDATA)>
<!ELEMENT rpmlist (all?,server?,client?)>
<!ELEMENT all (rpm+)>
<!ELEMENT server (rpm+)>
<!ELEMENT client (rpm+)>
<!ELEMENT rpm (#PCDATA)>
<!ATTLIST rpm distro CDATA #IMPLIED>
<!ATTLIST rpm version CDATA #IMPLIED>
<!ELEMENT oda (shortcut*,fieldnames*)>
<!ELEMENT shortcut (#PCDATA)>
<!ELEMENT fieldnames (#PCDATA)>

=== oscar-cluster/oscar/packages/kernel_picker/config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE package SYSTEM "../package.dtd">
<package>

<!--
      Copyright (c) 2002 The Trustees of Indiana University.  
                         All rights reserved.
      
      This file is part of the OSCAR software package.  For license
      information, see the COPYING file in the top level directory of the
      OSCAR source distribution.
     
      $Id: config.xml,v 1.3 2002/11/02 00:45:44 bligneri Exp $
      -->

  <name>kernel_picker</name>

  <version>
    <major>1</major>
    <minor>1</minor>
    <subversion>0</subversion>
    <release>1</release>
    <epoch>1</epoch>
  </version>

  <class>included</class>
  <installable>1</installable>

  <summary>A Perl script to substitute a kernel into an OSCAR (SIS) image.</summary>
  <license>GPL</license>
  <copyright>2002</copyright>
  <group>Application/System</group>
  <url>http://oscar.ncsa.uiuc.edu/</url>
  <packager>
    <name>NCSA</name>
    <email>oscar-users@lists.sourceforge.net</email>
  </packager>
  <vendor>NCSA</vendor>

  <description>kernel_picker allows you to substitute a given kernel
into your OSCAR (SIS) image prior to building your nodes.  If executed
with no command line options, you will be prompted for all required
information.  You can also specify command line options for (mostly)
non-interactive execution.  Any necessary information that you do not
give via an option will cause the program to prompt you for that
information.</description>

  <rpmlist>
    <server>
      <rpm>systemconfigurator</rpm>
      <rpm>perl</rpm>
      <rpm>kernel_picker</rpm>
    </server>
  </rpmlist>

</package>

=== oscar-cluster/oscar/packages/loghost/config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE package SYSTEM "../package.dtd">
<package>

<!--
      Copyright (c) 2002 The Trustees of Indiana University.  
                         All rights reserved.
      
      This file is part of the OSCAR software package.  For license
      information, see the COPYING file in the top level directory of the
      OSCAR source distribution.
     
      $Id: config.xml,v 1.3 2002/11/02 00:45:44 bligneri Exp $
      -->

  <name>loghost</name>

  <version>
    <major>1</major>
    <minor>0</minor>
    <subversion>0</subversion>
    <release>1</release>
    <epoch>1</epoch>
  </version>

  <class>included</class>
  <installable>1</installable>

  <summary>Configures server to accept remote syslog entries</summary>
  <license>GPL</license>
  <copyright>2002</copyright>
  <group>Applications/System</group>
  <packager>
    <name>Jeremy Enos</name>
    <email>jenos@ncsa.uiuc.edu</email>
  </packager>
  <vendor>NCSA</vendor>

  <description>loghost configures syslog settings.</description>

  <rpmlist>
    <server> 
      <rpm>loghost</rpm>
    </server>
  </rpmlist>

</package>
